name: "Terraform Plan"

on:
  push:
    branches: [master]
  workflow_dispatch:

env:
  TF_WORKSPACE: "terraform-github-actions"
  CONFIG_DIRECTORY: "./"

jobs:
  plan:
    name: Terraform plan
    runs-on: ubuntu-latest

    env:
      TF_WORKSPACE: "terraform-github-actions"
      CONFIG_DIRECTORY: "./"
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      TF_VAR_aws_region: ${{ secrets.AWS_REGION }}
      TF_VAR_web_domain_name: ${{ secrets.WEB_DOMAIN_NAME }}
      TF_VAR_web_subdomain_name: ${{ secrets.WEB_SUBDOMAIN_NAME }}
      TF_VAR_cloudflare_api_token: ${{ secrets.CLOUDFLARE_API_TOKEN }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Terraform Init
        run: terraform init

      - name: Select Terraform Workspace
        run: terraform workspace select $TF_WORKSPACE || terraform workspace new $TF_WORKSPACE

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan

      # - run: terraform apply -auto-approve
      # - name: Terraform Apply
      #   run: terraform apply -auto-approve
      #   env:
      #       TF_VAR_cloudflare_api_token: ${{ secrets.CLOUDFLARE_API_TOKEN }}
