name: Deploy Terraform

on:
  push:
    branches:
      - main  # Trigger when changes are pushed to main
  workflow_dispatch:  # Allow manual trigger from GitHub UI

jobs:
  terraform:
    name: Terraform Apply
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.9.8 

    # - name: Terraform Init
    #   run: terraform init

    # - name: Terraform Validate
    #   run: terraform validate

    # - name: Terraform Plan
    #   run: terraform plan

    # - name: Terraform Apply
    #   run: terraform apply -auto-approve
    #   env:
    #     TF_VAR_example_variable: ${{ secrets.TF_VAR_EXAMPLE_VARIABLE }}
